tienda/config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :currencies
  resources :spiders
  resources :data
  resources :scrapies
  resources :stores
  resources :estados
  resources :changes
  

  resources :tipos
  get 'session/new'

  resources :purchases
  resources :users
  resources :cities
  resources :countries
  resources :marcas
  resources :productos
  root 'productos#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  get 'find_producto' => 'productos#find_producto'
  get 'productos_por_marca_tipo' => 'productos#productos_por_marca_tipo'
  get 'add_to_card/:producto_id' => 'purchases#add_to_card', as: :add_to_card
  get 'show_card' => 'purchases#show_card'
  get 'session/new'
  get    'login'   => 'session#new'
  post   'login'   => 'session#create'
  delete 'logout'  => 'session#destroy'  
  get 'my_perfil' => 'users#my_perfil'
  get 'crear' => 'payment#create', as: :crear
  get "respuesta" => 'payment#respuesta', as: :respuesta
  post "confirmacion" => 'payment#confirmacion', as: :confirmacion
  #get "compras" => 'purchases#mis_compras', as: :compras
  get "panel_user" => 'users#panel_user', as: :panel_user
  get "panel_admin" => 'purchases#panel_admin', as: :panel_admin
  get "admin_ventas" => 'payment#admin_ventas', as: :admin_ventas
  get 'crear_pago' => 'purchases#crear_pago', as: :crear_pago
  get 'extract/:id' => 'spiders#extract', as: :extract
  get 'traer_data/:id' => 'spiders#traer_data', as: :traer_data
  post 'asignar_spider/origen/destino' => 'spiders#asignar_spider', as: :asignar_spider
  get 'productos_por_tipo' => 'productos#productos_por_tipo'  
  get 'productos_por_marca' => 'productos#productos_por_marca'  
  post 'to_cart/producto_id/quantity/cart_id' => 'carts#to_cart', as: :to_cart
  get 'show_cart' => 'carts#show_cart'
  get 'borrar_item' => 'carts#borrar_item', as: :borrar_item
  get 'compras' => 'payment#compras', as: :compras
end

tienda/app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :producto
  belongs_to :user
  belongs_to :payment
  belongs_to :estado
end

tienda/app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :producto
end

tienda/app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :users
end

tienda/app/models/country.rb
class Country < ActiveRecord::Base
	has_many :cities
	belongs_to :currency
end

tienda/app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :countries
	has_many :spiders
	has_many :productos
end

tienda/app/models/datum.rb
class Datum < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
end

tienda/app/models/estado.rb
class Estado < ActiveRecord::Base
    has_many :payments
    has_many :carts
end

tienda/app/models/marca.rb
class Marca < ActiveRecord::Base
	has_many :productos
	has_many :scrapies
end

tienda/app/models/marca_tipo.rb
class MarcaTipo < ActiveRecord::Base
  belongs_to :tipo
  belongs_to :marca
  has_many :productos
  has_many :spiders
end

tienda/app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :estado
  belongs_to :user
  has_many :carts
  def detalle
  	return Purchase.where(:agrupador => self.id+200)
  end
end

tienda/app/models/producto.rb
class Producto < ActiveRecord::Base	
	belongs_to :marca
	belongs_to :tipo
	has_many :change
	belongs_to :marca_tipo
	belongs_to :currency
	has_many :carts
	def divisa
		valor_divisa = 0
		case self.moneda
		when "€"
			valor_divisa= 3304.81
		when "$"
			valor_divisa = 2957.56
		end
		return valor_divisa
	end	
end

tienda/app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :producto 
  belongs_to :estado
end

tienda/app/models/scrapy.rb
class Scrapy < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
end

tienda/app/models/spider.rb
class Spider < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
  belongs_to :currency
  belongs_to :marca_tipo
end

tienda/app/models/store.rb
class Store < ActiveRecord::Base
	has_many :scrapies
end

tienda/app/models/tipo.rb
class Tipo < ActiveRecord::Base
	has_many :productos
	has_many :scrapies
end

tienda/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :city
  has_many :purchases
  has_many :payments
  has_many :carts
end

tienda/app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    permiso(current_user, 1)
    @marcas = Marca.all
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
    permiso(current_user, 1)
  end

  # GET /marcas/new
  def new
    permiso(current_user, 1)
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
    permiso(current_user, 1)
  end

  # POST /marcas
  # POST /marcas.json
  def create
    permiso(current_user, 1)
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca was successfully created.' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    permiso(current_user, 1)
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: 'Marca was successfully updated.' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    permiso(current_user, 1)
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_params
      params.require(:marca).permit(:nombre, :url_imagen, :url)
    end
end

tienda/app/helpers/carts_helper.rb
module CartsHelper
	def numero_cart
		return Cart.where.not(:estado_id => 4).where(:user_id => current_user).count
	end
end

tienda/app/helpers/data_helper.rb
module DataHelper
end

tienda/app/helpers/marcas_helper.rb
module MarcasHelper
end

tienda/app/helpers/tipos_helper.rb
module TiposHelper	
	
end

tienda/app/helpers/users_helper.rb
module UsersHelper
end

tienda/app/views/marcas/_form.html.erb
<%= form_for(@marca) do |f| %>
  <% if @marca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
      <% @marca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :url_imagen %><br>
    <%= f.text_field :url_imagen %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tienda/app/views/marcas/edit.html.erb
<h1>Editing Marca</h1>

<%= render 'form' %>

<%= link_to 'Show', @marca %> |
<%= link_to 'Back', marcas_path %>

tienda/app/views/marcas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Marcas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Url imagen</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= marca.nombre %></td>
        <td><%= marca.url_imagen %></td>
        <td><%= marca.url %></td>
        <td><%= link_to 'Show', marca %></td>
        <td><%= link_to 'Edit', edit_marca_path(marca) %></td>
        <td><%= link_to 'Destroy', marca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marca', new_marca_path %>

tienda/app/views/marcas/new.html.erb
<h1>New Marca</h1>

<%= render 'form' %>

<%= link_to 'Back', marcas_path %>

tienda/app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @marca.nombre %>
</p>

<p>
  <strong>Url imagen:</strong>
  <%= @marca.url_imagen %>
</p>

<p>
  <strong>Url:</strong>
  <%= @marca.url %>
</p>

<%= link_to 'Edit', edit_marca_path(@marca) %> |
<%= link_to 'Back', marcas_path %>