tienda/config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :currencies
  resources :spiders
  resources :data
  resources :scrapies
  resources :stores
  resources :estados
  resources :changes
  

  resources :tipos
  get 'session/new'

  resources :purchases
  resources :users
  resources :cities
  resources :countries
  resources :marcas
  resources :productos
  root 'productos#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  get 'find_producto' => 'productos#find_producto'
  get 'productos_por_marca_tipo' => 'productos#productos_por_marca_tipo'
  get 'add_to_card/:producto_id' => 'purchases#add_to_card', as: :add_to_card
  get 'show_card' => 'purchases#show_card'
  get 'session/new'
  get    'login'   => 'session#new'
  post   'login'   => 'session#create'
  delete 'logout'  => 'session#destroy'  
  get 'my_perfil' => 'users#my_perfil'
  get 'crear' => 'payment#create', as: :crear
  get "respuesta" => 'payment#respuesta', as: :respuesta
  post "confirmacion" => 'payment#confirmacion', as: :confirmacion
  #get "compras" => 'purchases#mis_compras', as: :compras
  get "panel_user" => 'users#panel_user', as: :panel_user
  get "panel_admin" => 'purchases#panel_admin', as: :panel_admin
  get "admin_ventas" => 'payment#admin_ventas', as: :admin_ventas
  get 'crear_pago' => 'purchases#crear_pago', as: :crear_pago
  get 'extract/:id' => 'spiders#extract', as: :extract
  get 'traer_data/:id' => 'spiders#traer_data', as: :traer_data
  post 'asignar_spider/origen/destino' => 'spiders#asignar_spider', as: :asignar_spider
  get 'productos_por_tipo' => 'productos#productos_por_tipo'  
  get 'productos_por_marca' => 'productos#productos_por_marca'  
  post 'to_cart/producto_id/quantity/cart_id' => 'carts#to_cart', as: :to_cart
  get 'show_cart' => 'carts#show_cart'
  get 'borrar_item' => 'carts#borrar_item', as: :borrar_item
  get 'compras' => 'payment#compras', as: :compras
end

tienda/app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :producto
  belongs_to :user
  belongs_to :payment
  belongs_to :estado
end

tienda/app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :producto
end

tienda/app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :users
end

tienda/app/models/country.rb
class Country < ActiveRecord::Base
	has_many :cities
	belongs_to :currency
end

tienda/app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :countries
	has_many :spiders
	has_many :productos
end

tienda/app/models/datum.rb
class Datum < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
end

tienda/app/models/estado.rb
class Estado < ActiveRecord::Base
    has_many :payments
    has_many :carts
end

tienda/app/models/marca.rb
class Marca < ActiveRecord::Base
	has_many :productos
	has_many :scrapies
end

tienda/app/models/marca_tipo.rb
class MarcaTipo < ActiveRecord::Base
  belongs_to :tipo
  belongs_to :marca
  has_many :productos
  has_many :spiders
end

tienda/app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :estado
  belongs_to :user
  has_many :carts
  def detalle
  	return Purchase.where(:agrupador => self.id+200)
  end
end

tienda/app/models/producto.rb
class Producto < ActiveRecord::Base	
	belongs_to :marca
	belongs_to :tipo
	has_many :change
	belongs_to :marca_tipo
	belongs_to :currency
	has_many :carts
	def divisa
		valor_divisa = 0
		case self.moneda
		when "€"
			valor_divisa= 3304.81
		when "$"
			valor_divisa = 2957.56
		end
		return valor_divisa
	end	
end

tienda/app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :producto 
  belongs_to :estado
end

tienda/app/models/scrapy.rb
class Scrapy < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
end

tienda/app/models/spider.rb
class Spider < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
  belongs_to :currency
  belongs_to :marca_tipo
end

tienda/app/models/store.rb
class Store < ActiveRecord::Base
	has_many :scrapies
end

tienda/app/models/tipo.rb
class Tipo < ActiveRecord::Base
	has_many :productos
	has_many :scrapies
end

tienda/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :city
  has_many :purchases
  has_many :payments
  has_many :carts
end

tienda/app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:name, :code, :value)
    end
end

tienda/app/helpers/carts_helper.rb
module CartsHelper
	def numero_cart
		return Cart.where.not(:estado_id => 4).where(:user_id => current_user).count
	end
end

tienda/app/helpers/currencies_helper.rb
module CurrenciesHelper
end

tienda/app/helpers/data_helper.rb
module DataHelper
end

tienda/app/helpers/tipos_helper.rb
module TiposHelper	
	
end

tienda/app/helpers/users_helper.rb
module UsersHelper
end

tienda/app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tienda/app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

tienda/app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Currencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
        <td><%= currency.name %></td>
        <td><%= currency.code %></td>
        <td><%= currency.value %></td>
        <td><%= link_to 'Show', currency %></td>
        <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
        <td><%= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Currency', new_currency_path %>

tienda/app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

tienda/app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @currency.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @currency.code %>
</p>

<p>
  <strong>Value:</strong>
  <%= @currency.value %>
</p>

<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>