tienda/config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :currencies
  resources :spiders
  resources :data
  resources :scrapies
  resources :stores
  resources :estados
  resources :changes
  

  resources :tipos
  get 'session/new'

  resources :purchases
  resources :users
  resources :cities
  resources :countries
  resources :marcas
  resources :productos
  root 'productos#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  get 'find_producto' => 'productos#find_producto'
  get 'productos_por_marca_tipo' => 'productos#productos_por_marca_tipo'
  get 'add_to_card/:producto_id' => 'purchases#add_to_card', as: :add_to_card
  get 'show_card' => 'purchases#show_card'
  get 'session/new'
  get    'login'   => 'session#new'
  post   'login'   => 'session#create'
  delete 'logout'  => 'session#destroy'  
  get 'my_perfil' => 'users#my_perfil'
  get 'crear' => 'payment#create', as: :crear
  get "respuesta" => 'payment#respuesta', as: :respuesta
  post "confirmacion" => 'payment#confirmacion', as: :confirmacion
  #get "compras" => 'purchases#mis_compras', as: :compras
  get "panel_user" => 'users#panel_user', as: :panel_user
  get "panel_admin" => 'purchases#panel_admin', as: :panel_admin
  get "admin_ventas" => 'payment#admin_ventas', as: :admin_ventas
  get 'crear_pago' => 'purchases#crear_pago', as: :crear_pago
  get 'extract/:id' => 'spiders#extract', as: :extract
  get 'traer_data/:id' => 'spiders#traer_data', as: :traer_data
  post 'asignar_spider/origen/destino' => 'spiders#asignar_spider', as: :asignar_spider
  get 'productos_por_tipo' => 'productos#productos_por_tipo'  
  get 'productos_por_marca' => 'productos#productos_por_marca'  
  post 'to_cart/producto_id/quantity/cart_id' => 'carts#to_cart', as: :to_cart
  get 'show_cart' => 'carts#show_cart'
  get 'borrar_item' => 'carts#borrar_item', as: :borrar_item
  get 'compras' => 'payment#compras', as: :compras
end

tienda/app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :producto
  belongs_to :user
  belongs_to :payment
  belongs_to :estado
end

tienda/app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :producto
end

tienda/app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :users
end

tienda/app/models/country.rb
class Country < ActiveRecord::Base
	has_many :cities
	belongs_to :currency
end

tienda/app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :countries
	has_many :spiders
	has_many :productos
end

tienda/app/models/datum.rb
class Datum < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
end

tienda/app/models/estado.rb
class Estado < ActiveRecord::Base
    has_many :payments
    has_many :carts
end

tienda/app/models/marca.rb
class Marca < ActiveRecord::Base
	has_many :productos
	has_many :scrapies
end

tienda/app/models/marca_tipo.rb
class MarcaTipo < ActiveRecord::Base
  belongs_to :tipo
  belongs_to :marca
  has_many :productos
  has_many :spiders
end

tienda/app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :estado
  belongs_to :user
  has_many :carts
  def detalle
  	return Purchase.where(:agrupador => self.id+200)
  end
end

tienda/app/models/producto.rb
class Producto < ActiveRecord::Base	
	belongs_to :marca
	belongs_to :tipo
	has_many :change
	belongs_to :marca_tipo
	belongs_to :currency
	has_many :carts
	def divisa
		valor_divisa = 0
		case self.moneda
		when "€"
			valor_divisa= 3304.81
		when "$"
			valor_divisa = 2957.56
		end
		return valor_divisa
	end	
end

tienda/app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :producto 
  belongs_to :estado
end

tienda/app/models/scrapy.rb
class Scrapy < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
end

tienda/app/models/spider.rb
class Spider < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
  belongs_to :currency
  belongs_to :marca_tipo
end

tienda/app/models/store.rb
class Store < ActiveRecord::Base
	has_many :scrapies
end

tienda/app/models/tipo.rb
class Tipo < ActiveRecord::Base
	has_many :productos
	has_many :scrapies
end

tienda/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :city
  has_many :purchases
  has_many :payments
  has_many :carts
end

tienda/app/helpers/carts_helper.rb
module CartsHelper
	def numero_cart
		return Cart.where.not(:estado_id => 4).where(:user_id => current_user).count
	end
end

tienda/app/helpers/data_helper.rb
module DataHelper
end

tienda/app/helpers/tipos_helper.rb
module TiposHelper	
	
end

tienda/app/views/partials/_listado_productos.html.erb
<div class="container">  
  <%= form_tag(find_producto_path, :method => 'get', :id => 'search-form', :class => 'navbar-form navbar-right' ) do %>
    <div class="row finder">
      <div class="col-sm-12">
        <div class="row">
          <h1 align="center">
            Que estas buscando ?
          </h1>
        </div>        
      </div> 
      <div class="col-sm-7">
        <div class="col-sm-4">
          <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
              <%= search_field_tag :searchProducto, params[:searchProducto], :class => 'form-control', :placeholder => 'Referencia'  %>   
            </div>
            <div class="col-md-1"></div>           
          </div>        
        </div>
        <div class="col-sm-4">
          <div class="row">
            <div class="col-sm-12">
              <%= text_field_tag :precio, '', :class => 'form-control', :placeholder => '450.000 CLP'%>
            </div>
          </div>        
        </div>
        <div class="col-sm-4">
          <div class="row">
            <div class="col-sm-12">
              <%= content_tag :button, "Buscar", :class => 'btn btn-primary btn-block'%>    
            </div>
          </div>       
        </div>        
      </div>
      <div class="col-sm-5">
        <div class="col-sm-4">
            <p>Orden:
              <%= link_to '⇧', controller: "productos", action: origen, marca_id: marca, tipo_id: tipo, orden: 'asc'%>
              <%= link_to '⇩', controller: "productos", action: origen, marca_id: marca, tipo_id: tipo, orden: 'desc'%> 
            </p>                          
        </div>              
        <div class="col-sm-4">
            <p>
              Precio: 
              <%= link_to '⇧', controller: "productos", action: origen, marca_id: marca, tipo_id: tipo, orden: 'asc', cambio_precio: 't', signo: '>'%>
              <%= link_to '⇩', controller: "productos", action: origen, marca_id: marca, tipo_id: tipo, orden: 'desc', cambio_precio: 't', signo: '<'%>
            </p> 
        </div>              
        <div class="col-sm-4">
            <p>
              <%= link_to 'Nuevos', controller: "productos", action: origen, marca_id: marca, tipo_id: tipo, orden: 'asc', nuevo: 't'%>
            </p> 
        </div>                      
      </div>
      <p>
    </div>

  <% end %>
</div>
<p>
<% if flash[:notice] %>
    <div class="container">
      <div class="row">
           <div class="col-sm-4"></div>
           <div class="col-sm-4">
              <div class="alert alert-danger">
                <%= flash[:notice] %>                
              </div>
           </div>
           <div class="col-sm-4"></div>
      </div>             
    </div>
<% else %>    
<% end %>
<p>
<div class="row">
  <% coleccion_productos.each do |producto| %>
    <div class="col-sm-4">
      <div class="row">
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-6">
            <img id = "zoom_02"src=<%= producto.imagen.split('|')[0]%> class="img-responsive" alt="a" style="width: 150px;0px;height:150px;">  
          </div>
          <div class="col-md-4">
            <div class="row">
              <%= link_to 'Ver más', producto_path(producto.id)%>           
            </div>
            <div class="row">
              <% if logged_in? %>
                <%= link_to 'add al carrito', add_to_card_path(:producto_id => producto.id)%>  
              <% else %>
              <% end %>                                                               
            </div>
          </div>
        </div>        
      </div>
      <div class="row">
        <small align="center">
          <%= producto.descripcion[0, 100]%>
           <b>
             <%= producto.currency.code%> 
             <%= producto.precio_min%>            
           </b> 
        </small>               
      </div>
      <p>
      <div class="row">
        <div class="row">
          <% if producto.cambio_precio == true%>
            Antes <%= price(producto, producto.precio_anterior, 1) %>
          <%else%>
          <% end %>
        </div>        
      </div>
    </div>

  <% end %>  
</div>


<!--     <% coleccion_productos.each do |producto| %>
      <div class="row">
        <div class="col-sm-4">
          <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4"><strong><%= producto.marca.nombre%></strong></div>
            <div class="col-md-4"></div>            
          </div>
          <div class="row">
            <div class="col-md-12">
              <img id = "zoom_02"src=<%= producto.imagen.split('|')[0]%> class="img-responsive" alt="a" style="width: 150px;0px;height:150px;">  
            </div>            
          </div>

          <div class="row">
           <h6>
             <label>
               <%= price(producto, producto.precio_venta, 1) %> | <%= price(producto, producto.precio_sin_iva_grv, 1) %>
             </label>
           </h6>   
          </div>

          <div class="row">
            <small>
              <%= producto.descripcion%>
            </small> 
          </div> 

          <div class="row">
            <div class="col-md-6">
              <%= link_to 'Ver más', producto_path(producto.id), :class => 'btn btn-success btn-sm' %>
            </div>
            <div class="col-md-6">
              <% if logged_in? %>
                <%= link_to 'Agregar al carrito', add_to_card_path(:producto_id => producto.id), :class => 'btn btn-primary btn-sm'%>  
              <% else %>
              <% end %>                            
            </div>            
          </div>

          <div class="row">
            <% if producto.cambio_precio == true%>
              Antes <%= price(producto, producto.precio_anterior, 1) %>
            <%else%>
            <% end %>
          </div>

          </div>        
      </div>    
      <p>      
      </div>
   <% end %>  
 -->

   <div class="row">
     <div class="col-sm-4"></div>
     <div class="col-sm-4">
       <div class="flickr_pagination">
        <%= will_paginate @productos, :container => false %>  
       </div>           
     </div>
     <div class="col-sm-4"></div>
   </div>

tienda/app/views/partials/_navegacion_panel_admin.html.erb
<%= render 'partes/menu_padre', tipos: tipos%>
<div class="container">
	<ul class="nav nav-tabs">
	  <li class="nav-item">
	  	<%= link_to 'Ventas', admin_ventas_path, :class => 'nav-link'%>
	  </li>	
	</ul>	
</div>

tienda/app/views/partials/_navegacion_panel_user.html.erb
<%= render 'partes/menu_padre', tipos: tipos%>
<div class="container">
	<ul class="nav nav-tabs">
	  <li class="nav-item">
	  	<%= link_to 'Compras', compras_path, :class => 'nav-link'%>
	  </li>	
	  <li class="nav-item">
	  	<%= link_to 'Account', edit_user_path(current_user), :class => 'nav-link'%>
	  </li>
	</ul>	
</div>

tienda/app/views/partials/_purchase_edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">           
      <%= form_for(purchase) do |f| %>
        <div class="row">
          <div class="col-xs-2"><img class="img-responsive" src=<%= purchase.producto.imagen%> class="img-responsive" alt="a" style="width: 180px;0px;height:210px;">
          </div>
          <div class="col-xs-4">
            <h6 class="product-name">
              <strong>Descripciòn del producto</strong>
            </h6>
            <%= purchase.producto.descripcion %>
          </div>
          <div class="col-xs-6">
            <div class="row">
              <div class="col-sm-4">
                <h6><strong> <%= price(purchase.producto, purchase.producto.precio_venta, 1) %>  <span class="text-muted">x</span></strong></h6>
              </div>
              <div class="col-sm-4">
                <%= f.number_field :cantidad, :class => '"form-control input-sm"'%> 
              </div>
              <div class="col-sm-4">
                = <%= price(purchase.producto, purchase.producto.precio_venta, purchase.cantidad) %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-xs-5">
                <div class="col-xs-4"><%= f.submit "Actualizar", :class => 'btn btn-success btn-sm'%></div>
              </div>
              <div class="col-xs-2">
                <%= link_to 'Eliminar', purchase, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm'%>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                Politicas de entrega. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex .                
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <hr>
        </div>            
      <% end %>           
    </div>    
  </div>  
</div>

tienda/app/views/partials/_table_purchases.html.erb
<div class="table-responsive">
    <table border="1" class="table table-striped table-bordered">
        <thead class="thead-inverse">
        	<tr>
        		<td align="center">Foto</td>
        		<td align="center">descripcion</td>
        		<td align="center">Cantidad</td>
        		<td align="center">estado</td>            		
        		<td align="center">Valor</td>
        	</tr>            
        </thead>
    <% purchases.each do |purchase| %>
    	<tr>
    		<td><img id = "zoom_02"src=<%= purchase.producto.imagen.split('|')[0]%> class="img-responsive" alt="a" style="width: 100px;0px;height:100px;"></td>
    		<td><%= purchase.producto.descripcion[0, 25]%></td>
    		<td><%= purchase.cantidad%></td>
    		<td><%= purchase.estado.nombre%></td>
    		<td><%= purchase.valor.round%></td>
    	</tr>
    <% end %>
    	<tr>
    		<td></td>
    		<td></td>
    		<td></td>
    		<td></td>
    		<td>Total <%=@valor_purchase%></td>
    	</tr>
    </table>    
</div>

tienda/app/views/partials/_table_venta.html.erb
<% total = 0%>
<div class="container">
    <div class="card">
        <div class="card-block">
            <div class="car-header">
                <% if origen == "admin"%>
                    <small>
                        <div class="row">
                            <div class="col-md-3">
                                <%= link_to "Usuario #{payment.user.user_name}", payment.user%>
                            </div>
                            <div class="col-md-3">
                               E-mail : <%= payment.user.email%>                                
                            </div>
                            <div class="col-md-3">
                               Ciudad : <%= payment.user.city.name%>, <%= payment.user.city.country.name%>                                 
                            </div>
                            <div class="col-md-3">
                               Direcciòn : <%= payment.user.addres%>                               
                            </div>
                        </div>                    
                    </small>
                <%else%>
                <%end%> 
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead class="thead-inverse">
                        <tr>
                            <td align="center">Foto</td>
                            <td align="center">descripcion</td>
                            <td align="center">Cantidad</td>
                            <td align="center">estado</td>                  
                            <td align="center">Valor</td>
                        </tr>            
                    </thead>
                <% purchases.each do |venta| %>
                    <tr>
                        <td><img id = "zoom_02"src=<%= venta.producto.imagen.split('|')[0]%> class="img-responsive" alt="a" style="width: 100px;0px;height:100px;"></td>
                        <td><%= venta.producto.descripcion[0, 25]%></td>
                        <td><%= venta.cantidad%></td>
                        <td>
                            <%= venta.estado.nombre%>
                            <% if venta.estado.id == 4 && current_user.nivel == 1%>
                                <a href=<%= venta.producto.url%>, class = 'btn btn-success btn-sm', target="_blank">
                                  Comprar
                                </a>      
                                <%= link_to "# de pedido", edit_purchase_path(venta)%>
                            <%end %>
                        </td>
                        <td><%= venta.valor.round%><% total = total + venta.valor.round %></td>
                    </tr>
                <% end %>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Total <%= total%></td>
                    </tr>
                </table>    
            </div>            
        </div>
    </div>

</div>