tienda/config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :currencies
  resources :spiders
  resources :data
  resources :scrapies
  resources :stores
  resources :estados
  resources :changes
  

  resources :tipos
  get 'session/new'

  resources :purchases
  resources :users
  resources :cities
  resources :countries
  resources :marcas
  resources :productos
  root 'productos#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
  get 'find_producto' => 'productos#find_producto'
  get 'productos_por_marca_tipo' => 'productos#productos_por_marca_tipo'
  get 'add_to_card/:producto_id' => 'purchases#add_to_card', as: :add_to_card
  get 'show_card' => 'purchases#show_card'
  get 'session/new'
  get    'login'   => 'session#new'
  post   'login'   => 'session#create'
  delete 'logout'  => 'session#destroy'  
  get 'my_perfil' => 'users#my_perfil'
  get 'crear' => 'payment#create', as: :crear
  get "respuesta" => 'payment#respuesta', as: :respuesta
  post "confirmacion" => 'payment#confirmacion', as: :confirmacion
  #get "compras" => 'purchases#mis_compras', as: :compras
  get "panel_user" => 'users#panel_user', as: :panel_user
  get "panel_admin" => 'purchases#panel_admin', as: :panel_admin
  get "admin_ventas" => 'payment#admin_ventas', as: :admin_ventas
  get 'crear_pago' => 'purchases#crear_pago', as: :crear_pago
  get 'extract/:id' => 'spiders#extract', as: :extract
  get 'traer_data/:id' => 'spiders#traer_data', as: :traer_data
  post 'asignar_spider/origen/destino' => 'spiders#asignar_spider', as: :asignar_spider
  get 'productos_por_tipo' => 'productos#productos_por_tipo'  
  get 'productos_por_marca' => 'productos#productos_por_marca'  
  post 'to_cart/producto_id/quantity/cart_id' => 'carts#to_cart', as: :to_cart
  get 'show_cart' => 'carts#show_cart'
  get 'borrar_item' => 'carts#borrar_item', as: :borrar_item
  get 'compras' => 'payment#compras', as: :compras
end

tienda/app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :producto
  belongs_to :user
  belongs_to :payment
  belongs_to :estado
end

tienda/app/models/change.rb
class Change < ActiveRecord::Base
  belongs_to :producto
end

tienda/app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :users
end

tienda/app/models/country.rb
class Country < ActiveRecord::Base
	has_many :cities
	belongs_to :currency
end

tienda/app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :countries
	has_many :spiders
	has_many :productos
end

tienda/app/models/datum.rb
class Datum < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
end

tienda/app/models/estado.rb
class Estado < ActiveRecord::Base
    has_many :payments
    has_many :carts
end

tienda/app/models/marca.rb
class Marca < ActiveRecord::Base
	has_many :productos
	has_many :scrapies
end

tienda/app/models/marca_tipo.rb
class MarcaTipo < ActiveRecord::Base
  belongs_to :tipo
  belongs_to :marca
  has_many :productos
  has_many :spiders
end

tienda/app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :estado
  belongs_to :user
  has_many :carts
  def detalle
  	return Purchase.where(:agrupador => self.id+200)
  end
end

tienda/app/models/producto.rb
class Producto < ActiveRecord::Base	
	belongs_to :marca
	belongs_to :tipo
	has_many :change
	belongs_to :marca_tipo
	belongs_to :currency
	has_many :carts
	def divisa
		valor_divisa = 0
		case self.moneda
		when "€"
			valor_divisa= 3304.81
		when "$"
			valor_divisa = 2957.56
		end
		return valor_divisa
	end	
end

tienda/app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :producto 
  belongs_to :estado
end

tienda/app/models/scrapy.rb
class Scrapy < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
end

tienda/app/models/spider.rb
class Spider < ActiveRecord::Base
  belongs_to :store
  belongs_to :marca
  belongs_to :tipo
  belongs_to :currency
  belongs_to :marca_tipo
end

tienda/app/models/store.rb
class Store < ActiveRecord::Base
	has_many :scrapies
end

tienda/app/models/tipo.rb
class Tipo < ActiveRecord::Base
	has_many :productos
	has_many :scrapies
end

tienda/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :city
  has_many :purchases
  has_many :payments
  has_many :carts
end

tienda/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def borrar_item
    cart = Cart.find(params[:cart_id])
    if cart
      cart.delete
    end
    redirect_to :back
  end
  def show_cart
    @tipos = Tipo.where(:id => Producto.select(:tipo_id).all)
    @carts = Cart.where.not(:estado_id => 4).where(:user_id => current_user) #busca todas las compras que no se han realizado o han sido fallidas
    @suma = 0
    @carts.each do |cart|
      @suma = @suma + cart.producto.precio_min * cart.quantity
    end    
  end
  def to_cart
    if params[:cart_id].to_i > 0
      c = Cart.find(params[:cart_id])
      if c
        c.quantity = params[:quantity]
        c.save
      end      
    else
      Cart.create(:producto_id => params[:producto_id], :user_id => current_user.id, :quantity => params[:quantity])
    end 
    redirect_to show_cart_path
  end
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:producto_id, :user_id, :payment_id, :estado_id)
    end
end

tienda/app/helpers/carts_helper.rb
module CartsHelper
	def numero_cart
		return Cart.where.not(:estado_id => 4).where(:user_id => current_user).count
	end
end

tienda/app/helpers/cities_helper.rb
module CitiesHelper
end

tienda/app/helpers/data_helper.rb
module DataHelper
end

tienda/app/helpers/tipos_helper.rb
module TiposHelper	
	
end

tienda/app/helpers/users_helper.rb
module UsersHelper
end

tienda/app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :producto_id %><br>
    <%= f.text_field :producto_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :payment_id %><br>
    <%= f.text_field :payment_id %>
  </div>
  <div class="field">
    <%= f.label :estado_id %><br>
    <%= f.text_field :estado_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tienda/app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

tienda/app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th>Producto</th>
      <th>User</th>
      <th>Payment</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.producto %></td>
        <td><%= cart.user %></td>
        <td><%= cart.payment %></td>
        <td><%= cart.estado %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

tienda/app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

tienda/app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Producto:</strong>
  <%= @cart.producto %>
</p>

<p>
  <strong>User:</strong>
  <%= @cart.user %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @cart.payment %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cart.estado %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>